language: generic
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env: CC=gcc-7 CXX=g++-7
script: ./configure && make && make test
branches:
  only:
  - master